language: elixir

elixir:
  - 1.11
  - 1.10
otp_release:
  - 23.0
  - 22.0
  - 21.0

jobs:
  allow_failures:
    - elixir: 1.11
      otp_release: 21.0
  fast_finish: true

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - mix compile
  - MIX_ENV=test mix compile

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix dialyzer
  - mix test
  - mix coveralls.travis --trace

# Leave only .plt files in build
before_cache:
  - mix deps.clean --all --build
  - mix clean --build

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build
    - priv/plts
